---
# tasks file for hypnos
- name: install akmods
  become: true
  package:
    name: akmods
    state: latest

- name: install dkms-r8168
  become: true
  community.general.copr:
    name: 'sunwire/dkms-r8168'
    includepkgs: dkms-r8168
