#SPDX-License-Identifier: MIT-0
---
# tasks file for xcb
- name: set mythfrontend to use XCB
  become: true
  lineinfile:
    path: /usr/share/applications/mythfrontend.desktop
    regexp: '^Exec=mythfrontend'
    line: Exec=mythfrontend -platform xcb
