---
# tasks file for dionysus
- name: install dionysus packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - cronie
    - openal-soft
    - pulseaudio-utils
    - SDL2-devel

- name: enable crond
  become: true
  systemd:
    state: started
    enabled: true
    masked: false
    name: crond.service

- name: copy monitors.xml to /var/lib/gdm/.config/
  become: true
  copy:
    src: monitors.xml
    dest: /var/lib/gdm/.config/monitors.xml
    owner: root
    group: root
    mode: 0644

- name: copy monitors.xml to $HOME/.config/
  copy:
    src: monitors.xml
    dest: "{{ ansible_env.HOME }}/.config/monitors.xml"
    owner: james
    group: james
    mode: 0644

- name: keep soundbar alive
  cron:
    name: "Keep soundbar alive"
    minute: "*/10"
    job: "/usr/bin/paplay /mnt/zeus/Archive/Linux/Dionysus/19999.wav"

- name: set mythfrontend to use XCB
  become: true
  lineinfile:
    path: /usr/share/applications/mythfrontend.desktop
    regexp: '^Exec=mythfrontend'
    line: Exec=mythfrontend -platform xcb