---
# tasks file for fedora-workstation
- name: set command-line arguments in grub2
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: GRUB_CMDLINE_LINUX="ipv6.disable=1 quiet"
  notify: run-grub2-mkconfig

- name: set static hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"

- name: copy lan ca certificate
  become: true
  copy:
    src: ca.crt
    dest: /etc/pki/ca-trust/source/anchors/ca.crt
    owner: root
    group: root
    mode: 0444
  notify: update ca trust

- name: disable tracker
  systemd_service:
    name: "{{ item }}"
    enabled: false
    state: stopped
    masked: true
    scope: user
  with_items:
    - tracker-miner-fs-3.service
    - tracker-miner-fs-control-3.service
    - tracker-miner-rss-3.service
    - tracker-writeback-3.service
    - tracker-xdg-portal-3.service
  notify:
    - kill tracker daemon
    - delete tracker cache

- name: add pgdev/jellyfin copr
  become: true
  community.general.copr:
    name: 'pgdev/jellyfin'

- name: install jellyfin-media-player and its dependencies
  become: true
  dnf:
    name:
      - qt5-qtquickcontrols
      - qt5-qtquickcontrols2
      - jellyfin-media-player
    state: latest

- name: remove desktop, public, and templates subdirectories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  with_items:
    - Desktop
    - Public
    - Screenshots
    - Templates

- name: create pipewire configuration subdirectories
  become: true
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/pipewire/client.conf.d
    - /etc/pipewire/pipewire-pulse.conf.d

- name: copy pipewire configuration files
  become: true
  copy:
    src: 10-normalize.conf
    dest: "{{ item }}"
    owner: root
    group: root
  loop:
    - /etc/pipewire/client.conf.d/10-normalize.conf
    - /etc/pipewire/pipewire-pulse.conf.d/10-normalize.conf
  notify: restart pipewire

- name: copy tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: james
    group: james
    mode: 0644

- name: copy tmux wrapper script
  become: true
  copy:
    src: t.sh
    dest: /usr/local/bin/t.sh
    owner: james
    group: james
    mode: 0755

- name: copy .vimrc
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    owner: james
    group: james
    mode: 0644

- name: set alias for tmux wrapper script
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    insertafter: '^# User specific environment$'
    line: "alias t=/usr/local/bin/t.sh"

- name: set color scheme to dark
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: set gtk theme to adwaita-dark
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"

- name: set background
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/gnome/blobs-d.svg'"

- name: set clock to 12h
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"

- name: set date in taskbar
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: set weekday in taskbar
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"

- name: enable right-mouse button clicking
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad"
    value: "'areas'"

- name: disable natural scrolling
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"

- name: enable tap to click
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: set display timeout to 15m
  dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 900"

- name: disable event sounds
  dconf:
    key: "/org/gnome/desktop/sound/event-sound"
    value: "false"

- name: set bell-style to none
  become: true
  lineinfile:
    path: /etc/inputrc
    regexp: '^#set bell-style none'
    line: 'set bell-style none'

- name: disable audible bell
  dconf:
    key: "/org/gnome/desktop/wm/preferences/audible-bell"
    value: "false"

- name: disable visual bell
  dconf:
    key: "/org/gnome/desktop/wm/preferences/visual-bell"
    value: "false"

- name: set ptyxis profile
  dconf:
    key: "/org/gnome/Ptyxis/profile-uuids"
    value: "['8ace1151de46338b9742684167297aff']"

- name: set default ptyxis profile
  dconf:
    key: "/org/gnome/Ptyxis/default-profile-uuid"
    value: "'8ace1151de46338b9742684167297aff'"

- name: set ptyxis apperance to follow system
  dconf:
    key: "/org/gnome/Ptyxis/interface-style"
    value: "'system'"

- name: set ptyxis font
  dconf:
    key: "/org/gnome/Ptyxis/use-system-font"
    value: "false"

- name: set ptyxis font
  dconf:
    key: "/org/gnome/Ptyxis/font-name"
    value: "'Monospace 12'"

- name: enable bolding of colors
  dconf:
    key: "/org/gnome/Ptyxis/Profiles/8ace1151de46338b9742684167297aff/bold-is-bright"
    value: "true"

- name: enable bolding of colors
  dconf:
    key: "/org/gnome/Ptyxis/Profiles/8ace1151de46338b9742684167297aff/label"
    value: "'Default'"

- name: move window buttons to right
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"

- name: unset alt+tab from 'switch-applications'
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-applications"
    value: "@as []"

- name: unset alt+tab from 'switch-applications-backward'
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
    value: "@as []"

- name: set alt+tab to 'switch-windows'
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"

- name: set alt+tab to 'switch-windows-backward'
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Alt>Tab']"

- name: disable location services
  dconf:
    key: "/org/gnome/system/location/enabled"
    value: "false"

- name: configure gnome favorites
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'mythfrontend.desktop', 'org.gnome.TextEditor.desktop', 'code.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Ptyxis.desktop']"

- name: disable gnome weather automatic location-sensing
  dconf:
    key: "/org/gnome/Weather/automatic-location"
    value: "false"

- name: set gnome weather location
  dconf:
    key: "/org/gnome/Weather/locations"
    value: "[<(uint32 2, <('Washington Dulles International Airport, United States of America', '', false, [(0.67984529717596465, -1.3518172479030162)], @a(dd) [])>)>]"

- name: set gnome shell weather location
  dconf:
    key: "/org/gnome/shell/Weather/locations"
    value: "[<(uint32 2, <('Washington DC, Washington-Dulles International Airport', 'KIAD', false, [(0.67953909224867171, -1.3517138724383084)], @a(dd) [])>)>]"

- name: set 'maximize window' key
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/maximize"
    value: "['<Super>Up']"
  changed_when: false  # this always gets marked as changed on apollo because it conflicts with the tiling assistant extension

- name: create ~/.mythtv
  file:
    path: "{{ ansible_env.HOME }}/.mythtv/"
    state: directory

- name: check if ~/.mythtv/config.xml exists
  stat:
    path: "{{ ansible_env.HOME }}/.mythtv/config.xml"
  register: config_xml_result

- name: copy ~/.mythtv/config.xml
  copy:
    src: config.xml
    dest: "{{ ansible_env.HOME }}/.mythtv/config.xml"
    owner: james
    group: james
    mode: 0644
  when: config_xml_result.stat.exists == false
